version: "3.3"
services:
  nginx:
    build: ./nginx
    image: nginx
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - /home/${LOGIN}/data/wp-files:/var/www/html
    restart: on-failure
  wp-php:
    build: ./wp-php
    image: wp-php
    container_name: wp-php
    volumes:
      - /home/${LOGIN}/data/wp-files:/var/www/html
    environment:
      - MAINDB=${MAINDB}
      - PASSWDDB=${PASSWDDB}
    restart: on-failure
  mariadb:
    build: ./mariadb
    image: mariadb
    container_name: mariadb
    volumes:
      - /home/${LOGIN}/data/wp-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_NEW_ROOT_PASSWORD=${MYSQL_NEW_ROOT_PASSWORD}
      - MAINDB=${MAINDB}
      - PASSWDDB=${PASSWDDB}
    restart: on-failure
networks:
  default:
volumes:
  wp-db:
    driver_opts:
      type: none
      device: /home/${LOGIN}/data/wp-db
      o: bind
  wp-files:
    driver_opts:
      type: none
      device: /home/${LOGIN}/data/wp-files
      o: bind