version: "3.9"  # optional since v1.27.0
services:
  nginx:
    build: ./nginx
    image: nginx
    ports:
      - "443:443"
      - "9000:9000"
    volumes:
      - /home/${LOGIN}/data/wp-files:/var/www/html
  wp-php:
    build: ./wp-php
    image: wp-php
    ports:
      - "9000:9000"
      - "3306:3306"
    volumes:
      - /home/${LOGIN}/data/wp-files:/var/www/html
  mariadb:
    build: ./mariadb
    image: mariadb
    ports:
      - "3306:3306"
    volumes:
      - /home/${LOGIN}/data/wp-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_NEW_ROOT_PASSWORD=${MYSQL_NEW_ROOT_PASSWORD}